<?php

namespace App\Models;

use App\Traits\FileHelper;
use App\Traits\HasApiWhere;
use Illuminate\Database\Eloquent\Model as EModel;

class Model extends EModel
{
    use FileHelper, HasApiWhere;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(static function ($model) {
            $constants = new \ReflectionClass($model);

            if ($constants->getConstant('UPLOADS')) {
                foreach (static::UPLOADS as $upload) {
                    $model->$upload = static::moveUploadedFile($model->$upload, get_class($model));
                }
            }
        });

        static::updating(static function ($model) {
            $oldModel = $model->getAttributes();

            $constants = new \ReflectionClass($model);

            if ($constants->getConstant('UPLOADS')) {
                foreach (static::UPLOADS as $upload) {
                    if ($oldModel[$upload] !== $model->$upload) {
                        static::deleteUploadedFile($model->$upload);
                        $model->$upload = static::moveUploadedFile($oldModel[$upload], get_class($model));
                    }
                }
            }

        });


    }
}
